# Generated by Django 5.1.5 on 2025-01-25 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=255)),
                ('physicianID', models.CharField(max_length=255)),
                ('admissionReason', models.TextField()),
                ('ward', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('admissionTime', models.DateTimeField()),
            ],
        ),
    ]
