# Generated by Django 5.1.5 on 2025-01-25 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=255)),
                ('condition', models.TextField()),
                ('triageCategory', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('arrivalTime', models.DateTimeField()),
                ('estimatedTreatmentTime', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Triaged', 'Triaged'), ('Discharged', 'Discharged'), ('Admitted', 'Admitted'), ('Awaiting Tests', 'Awaiting Tests'), ('MIA', 'MIA')], default='Triaged', max_length=255)),
            ],
        ),
    ]
