# Generated by Django 5.1.5 on 2025-01-26 02:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_missingpatient_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(blank=True, max_length=255, null=True)),
                ('imaging', models.CharField(blank=True, max_length=255, null=True)),
                ('referral', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=255)),
                ('roomNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('startTime', models.DateTimeField()),
                ('estimatedEndTime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Triaged', 'Triaged'), ('Discharged', 'Discharged'), ('Admitted', 'Admitted'), ('Processing', 'Processing'), ('Awaiting Tests', 'Awaiting Tests'), ('MIA', 'MIA')], default='Triaged', max_length=255),
        ),
        migrations.CreateModel(
            name='PendingPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=255)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pending')),
            ],
        ),
    ]
