# Generated by Django 5.1.5 on 2025-01-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pending_processpatient_alter_patient_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingpatient',
            old_name='status',
            new_name='pending',
        ),
    ]
