# Generated by Django 5.1.5 on 2025-01-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_status_pendingpatient_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
